services:
  mysql-cart:
    image: mysql:latest
    restart: always
    container_name: mysql-cart
    hostname: "mysql-cart"
    environment:
      MYSQL_DATABASE: 'cartdb'
      MYSQL_USER: 'cartuser_mysql'
      MYSQL_PASSWORD: 'mSq@2024*PtEc'
      MYSQL_ROOT_PASSWORD: 'mSqR@@t*2024p@s'
    ports:
      - '3308:3306'
    networks:
      - my_network


  mscart:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-cart
    hostname: "ms-cart"
    environment:
      MYSQL_HOSTNAME: mysql-cart
      MYSQL_PORT: 3308
      MSUSER_HOSTNAME: ms-user
      MSUSER_PORT: 8080
    ports:
      - 8082:8082
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true