services:
  mysql-cart:
    image: mysql:latest
    restart: always
    container_name: mysql-cart
    hostname: "mysql-cart"
    environment:
      MYSQL_DATABASE: 'cartdb'
      MYSQL_USER: 'cartuser_mysql'
      MYSQL_PASSWORD: 'mSq@2024*PtEc'
      MYSQL_ROOT_PASSWORD: 'mSqR@@t*2024p@s'
    ports:
      - '3308:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-cart" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - my_network


  mscart:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql-cart:
        condition: service_healthy
    hostname: "ms-cart"
    environment:
      MYSQL_HOSTNAME: mysql-cart
      MYSQL_PORT: 3306
      MSUSER_HOSTNAME: ms-cart
      MSUSER_PORT: 8082
    ports:
      - 8082:8082
    networks:
      - my_network

  sonarqube:
    image: sonarqube:community
    hostname: "sonarqube"
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9001:9000"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  my_network:
    driver: bridge
    external: true